### ISSUE TITLE
Update scripts to process latest platforms for watched slots

### ISSUE THREAD

**Issue by alex-t-grecu** [mmazurekgda/nightly-status-checker#5]
The reporting script needs updating to be able to process tha latest platform tags for the watched nightly slots. Ideally the script should be able to get the list of platforms from the nightly status tables and avoid any hardcoding.

**Comment by alex-t-grecu** [comment]
HI Michal, did you envisage or would accept to transform the `--platforms` argument into a list of platform filters with specific grammar to apply for specific slots?
I assume the platform tag will always consist on the following tokens joined by dash: CPU architecture, OS name/version, compiler (and) version, and indicator of production/debug version as suffixes `-opt` and `'-dbg`, respectively.
Then I would propose the script to look by default at all `platforms` listed in the JSON response and apply the filters given through the platforms argument when present.
The grammar could be simple like [[slot_name] ::] [!] [arch|*]-[os|*]-[gcc|*]-[opt|dbg|*], where the `*` character would be replaced by a non-greedy regexp (i.e. `.+?`), the slot name prefix would be optional but necessary to define filters for specific slots only and `!` would indicate that filter must be used to exclude matching platforms from the report.

However this looks a bit complex to implement for such a script. I thought of another solution with a `config.py` module with the default values for the slots, platforms and maybe projects to check which you take precendent over hardcoded value when present. And maybe have a supplemental argument for the script to trigger the automatic generation of this module based on values gathered from the nightlies API calls.

While waiting for a decision from you on the ideas above I will try to implement the latter and use it for my end-of-shift report.

**Comment by alex-t-grecu** [comment]
Second scenario with external config module generation and improved compression of the platform tags can be found in [this fork](https://github.com/alex-t-grecu/nightly-status-checker). 
I added the `mkconfig` command which generates `config.py` modules. This module  is imported at run-time if present so slots, projects and platform can also be customized trough it. 
The platform tag compression tries to reproduce the order of the platforms as in the nightly table and replaces (by `*`) as much as possible of the common part of the tag name between the current and the previous tag name in the list. Suffixes of form `!<number>` are added to make table heads unique for pandas.DataFrame.

**Comment by mmazurekgda** [comment]
Hi @alex-t-grecu, thank you very much. I have included your changes in #6 and  #7
